server:
  port: 8080

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.wallet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
