package com.wallet.enums;

public enum AmlFlagType {
    HIGH_VALUE_TRANSACTION,
    HIGH_FREQUENCY_TRANSACTION,
    SUSPICIOUS_ACTIVITY,
    FRAUDULENT_ACTIVITY,
    LARGE_TRANSACTION,
    STRUCTURING,
    UNUSUAL_PATTERN,
    HIGH_FREQUENCY
    OTHER,
    NOT_SUSPICIOUS
}